### ISSUE TITLE
Expose typings for agora-rtm-sdk

### ISSUE THREAD

**Issue by fandy** [AgoraIO/RTM#100]
Many core types aren't exposed in the package.  It'd be very useful to have them exported for use in components.

**Comment by yoreland** [comment]
Thanks for suggestion, can you just raise some examples?

**Comment by fandy** [comment]
Like `RtmStatusCode`, `RtmMessage`, `RtmEvents`, `RtmClient` from the top of my head.

I don't see the harm in exporting all the types :)

**Comment by iFwu** [comment]
> Like `RtmStatusCode`, `RtmMessage`, `RtmEvents`, `RtmClient` from the top of my head.
> 
> I don't see the harm in exporting all the types :)

@fandy We'll release a version with these types in the `index.d.ts` before the end of this month.
You can do some change to the `index.d.ts` for exporting these types. Find `agora-rtm-sdk` folder under `node_modules` and change the last few lines of `index.d.ts` like below.
Before:
```TypeScript
export = AgoraRTM;
export as namespace AgoraRTM;
```
```TypeScript
export default AgoraRTM;
export as namespace AgoraRTM;
export type { RtmClient, RtmEvents, RtmStatusCode, RtmChannel, RtmMessage };
```

**Comment by fandy** [comment]
Thanks @iFwu , only problem is I'm ignoring the node_modules folder in Git, but I'll wait for your team's updates 👍

**Comment by iFwu** [comment]
@fandy "agora-rtm-sdk" v1.4.0 has been published on NPM.
