### ISSUE TITLE
Update your Wechat Miniapp Demo

### ISSUE THREAD

**Issue by jun1st** [AgoraIO/RTM#117]
please update your wechat mini app demo,  it doesn't work.

even the sdk file name doesn't match, 

download the latest sdk, and open the project with weapp dev tools,  doesn't pass compilation.

**Comment by artiely** [comment]
Error: module "lib/rtm.miniapp.js" is not defined


在 Agora.io 注册账号，并创建自己的测试项目，获取 App ID。如需获取 Token，请启用 App Certificate

下载本页示例程序

打开 utils 文件夹，在 config.js 文件中填入获取到的 App ID： const APPID = 'abcdefg'

在 Agora 官网下载 RTM sdk 压缩包，并将文件保存在本示例程序的 lib 文件夹下，并重命名为 rtm.miniapp.js

启动微信开发者工具并导入该示例程序

如上 运行报错

**Comment by jun1st** [comment]
> Error: module "lib/rtm.miniapp.js" is not defined
> 
> 在 Agora.io 注册账号，并创建自己的测试项目，获取 App ID。如需获取 Token，请启用 App Certificate
> 
> 下载本页示例程序
> 
> 打开 utils 文件夹，在 config.js 文件中填入获取到的 App ID： const APPID = 'abcdefg'
> 
> 在 Agora 官网下载 RTM sdk 压缩包，并将文件保存在本示例程序的 lib 文件夹下，并重命名为 rtm.miniapp.js
> 
> 启动微信开发者工具并导入该示例程序
> 
> 如上 运行报错

even you download the latest sdk, change the sdk file name,   still have the same error,

**Comment by artiely** [comment]
找到问题原因了，必须开启ES6转ES5和增强编译，或者手动吧代码修改掉，搜索并替换成ES5 `?.`及`cath{}`
