### ISSUE TITLE
RTM Web Login is success only when account name is passed with channel name

### ISSUE THREAD

**Issue by gauravtripathi86** [AgoraIO/RTM#129]
Login is failing if I am passing any random string in  account name (uid) but getting successful when I am passing channel name in account name (uid)

**Comment by plutoless** [comment]
you mean how you generate rtm token?

**Comment by gauravtripathi86** [comment]
TRM token I generated from Dashboard, Using same APPId used for generating token.When I am giving random name in the account name, LOGIN_FAILURE is coming. But if I am passing channel name used for generating token it is succesful. 

But the problem is I should not use channel name as account name(user id) because as soon as some did it again first user will be logged out as account name is same again (channel name)

**Comment by plutoless** [comment]
@gauravtripathi86 the temp token generated in dashboard is for RTC. for design purpose we are reusing the token generation algorithm in which channel field is reused as account name for RTM. So you can generate a temp token in dashboard while using your account id as channel name, this is technically feasible.

**Comment by gauravtripathi86** [comment]
So you are saying for each user in the channel temp token should be different. i thought it is common for all joining same channel.

**Comment by plutoless** [comment]
yes because if you are generating the token for RTM, the channel field you entered is actually RTM account name. For different user it's for sure different.

**Comment by gauravtripathi86** [comment]
Ok, is this behaviour WEB specific because I think for iOS and Android I am able to use common token.

**Comment by plutoless** [comment]
@gauravtripathi86 no if you are using same account the new login user will kick off the users logged in on other platforms.

**Comment by gauravtripathi86** [comment]
@plutoless Thanks a lot! I really appreciate the quick and working response. I am sure I will definitely need your help in the future.  
:)

**Comment by plutoless** [comment]
no problem :) enjoy using sdk.
