### ISSUE TITLE
Login error: 5

### ISSUE THREAD

**Issue by niravramani72** [AgoraIO/RTM#131]
I downloaded ios demo for RTM and replace app id with my app id. And document says for development nil token will work.
I write anything in account and try to login it keeps giving "Login Error: 5"
can you help me with this?

**Comment by plutoless** [comment]
you will need to turn off app certificate if you want to login w/o token. otherwise you will need to sign a token when you login

**Comment by niravramani72** [comment]
In Dashboard I can not turn off primary certificate as it is not giving option to disabled it. How can I do that?

**Comment by niravramani72** [comment]
> you will need to turn off app certificate if you want to login w/o token. otherwise you will need to sign a token when you login

In Dashboard I can not turn off primary certificate as it is not giving option to disabled it. How can I do that?

**Comment by plutoless** [comment]
i think you can create a new project and select no token option

**Comment by niravramani72** [comment]
> i think you can create a new project and select no token option

Thank you It did work. I'm closing this issue.
