### ISSUE TITLE
RTM:ERROR No available edge address to connect

### ISSUE THREAD

**Issue by deevannaveed** [AgoraIO/RTM#144]
When I try to login to Agora RTM on WeChat miniprogram, I get the following error. 
We are using Taro.js for our miniprogram.

![image](https://user-images.githubusercontent.com/25431946/120571665-0bc90900-c434-11eb-9295-5724ad5b3fb8.png)

**Comment by plutoless** [comment]
这边小程序的域名白名单有配置吗

**Comment by deevannaveed** [comment]
> 这边小程序的域名白名单有配置吗

Thanks for you reply, the Problem was resolved by using the right SDK, I was using the Web SDK while there is a special SDK for WeChat.
