### ISSUE TITLE
User leaves channel after 30 sec while app is in background

### ISSUE THREAD

**Issue by AV2RY** [AgoraIO/RTM#151]
Hi, I noticed that a user leaves channel while his app in background after 30 secs. Is there a way to avoid that? Thanks.

**Comment by imnhsang** [comment]
Hi @AV2RY, I am having the problem same. Do you solve it? and How?

**Comment by plutoless** [comment]
@imnhsang which platform are you using?

**Comment by imnhsang** [comment]
@plutoless I am using iOS and React Native frameworks

**Comment by plutoless** [comment]
i believe that's system behavior that apple does not allow long time living tasks running in background when the app is not active.

**Comment by imnhsang** [comment]
well. I will check, thank you @plutoless pl
