### ISSUE TITLE
History chat messages, i am using "agora-rtm-sdk" version "1.4.2", how to store and reload message history?

### ISSUE THREAD

**Issue by trananhchuong** [AgoraIO/RTM#154]
I have reference function "SendMessageOptions" configure "enableHistoricalMessaging=true" but it's not working for me

**Comment by plutoless** [comment]
hi @trananhchuong you will need corresponding server-side restful api to get the message history. the apis are not yet available on en docs though. you can reach to support team if needed.

**Comment by trananhchuong** [comment]
i see, thank you @plutoless
