### ISSUE TITLE
Error dynamic use static key

### ISSUE THREAD

**Issue by imtiazwazir** [AgoraIO/RTM#182]
Uncaught (in promise) AgoraRTCException: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: dynamic use static key

Any help regarding following error, I am using null for the API and its in testing, did use new API key but no help.

**Comment by plutoless** [comment]
@imtiazwazir a simple way would be to turn off token feature (or create a new project w/o token enabled in console).
and maybe you can take a look here to understand how to use token when using agora sdk

**Comment by imtiazwazir** [comment]
I have been using a project where the token was disabled, and it got enabled automatically, so creating a new project solved the issue.
