### ISSUE TITLE
I have download Real-time Messaging SDK(Beta) sample code run what is value enter account login 

### ISSUE THREAD

**Issue by Lalitchaudhary2** [AgoraIO/RTM#25]

**Comment by plutoless** [comment]
just provide any string id. It's the account which others can send you p2p messages.

**Comment by AbhijithEnfinTechnologies** [comment]
Hi, we have the same issue. when give a unique userId its showing : err: LOGIN_ERR_INVALID_TOKEN
Error code : 5.
please help me to resolve it

**Comment by AbhijithEnfinTechnologies** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/57350044/71152613-ec004e00-225c-11ea-8f7f-db6ded8c8627.png)

Please find the attachment its from sample code

**Comment by plutoless** [comment]
where does your token come from?

**Comment by AbhijithEnfinTechnologies** [comment]
from our server side

**Comment by plutoless** [comment]
could you pls give me an example token you calculated. plus corresponding account you are using

**Comment by plutoless** [comment]
let's discuss in this thread instead https://github.com/AgoraIO/RTM/issues/49
