### ISSUE TITLE
The vendor enabled the dynamic key, but uses the static key.

### ISSUE THREAD

**Issue by carior** [AgoraIO/RTM#28]

**Comment by plutoless** [comment]
it usually means you have enabled security token, but didn't take it while login RTM. For details pls take a look https://docs.agora.io/en/Real-time-Messaging/RTM_key?platform=All%20Platforms

**Comment by carior** [comment]
> it usually means you have enabled security token, but didn't take it while login RTM. For details pls take a look https://docs.agora.io/en/Real-time-Messaging/RTM_key?platform=All%20Platforms

Can I set token not to be used? How should I set it?

**Comment by plutoless** [comment]
https://docs.agora.io/en/Real-time-Messaging/API%20Reference/RTM_cpp/classagora_1_1rtm_1_1_i_rtm_service.html#a2433a0babbed76ab87084d131227346b

**Comment by kush3107** [comment]
> it usually means you have enabled security token, but didn't take it while login RTM. For details pls take a look https://docs.agora.io/en/Real-time-Messaging/RTM_key?platform=All%20Platforms

I cannot access the link. Can you please explain what needs to be done exactly.

**Comment by plutoless** [comment]
@kush3107  is there anything still not clear to you?

**Comment by kush-prof** [comment]
Nothing, thanks. I figured that out.

**Comment by kush3107** [comment]
No thanks, I figured that out. :)

**Comment by plutoless** [comment]
sounds great :)

**Comment by maheshpraj** [comment]
I also getting same issue. please how can solve it. i try but cant works.
var client = AgoraRTM.createInstance(option.appID);
client.login({ token: mToken, uid: uid.toString() }).then(function () {
	console.log('AgoraRTM client login success');
}).catch(function (err) {
	console.log('AgoraRTM client login failure', err);
});

**Comment by dhananjaynegi123** [comment]
Hi I am facing same issue, RtmUnauthenticatedError.

Please help me out. How to fix it?

**Comment by dhananjaynegi123** [comment]
@kush please help me out how to fix the problem.

**Comment by KuSh** [comment]
> @KuSh please help me out how to fix the problem.

Wrong mention !

**Comment by gregsadetsky** [comment]
To solve this: go to [your projects](https://console.agora.io/projects), then click the Create button. Pick the "Testing mode: APP ID" option -- you can then use this App ID to authentify. As noted, this should only be used during testing i.e.  in production, you should be using the App ID to dynamically generate tokens.

**Comment by iamwavefly** [comment]
this is the solution -> await client.login({uid, token})
replace your app id with your dynamic token

**Comment by imtiazwazir** [comment]
Still facing this issue when in development/testing environment. 

`Uncaught (in promise) AgoraRTCException: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: dynamic use static key`

**Comment by euhansarkar** [comment]
When I got this error. after a lot of google searching, I don't get any solution, then I just create a new project. then it's working.

**Comment by padaliya-Kapil** [comment]
@euhansarkar let me try the same

**Comment by deepto98** [comment]
@euhansarkar Thanks, I was facing the same issue, trying to code along with Dennis Ivy's  [livestream](https://www.youtube.com/live/QvNzL_FmzLQ?feature=share). It got solved after  creating a new project.

**Comment by pedroeagle** [comment]
@euhansarkar @padaliya-Kapil @deepto98 have you guys faced this bug again, after recreating the project? this solution also works for me but I'm afraid to get this back after some time
