### ISSUE TITLE
communication 

### ISSUE THREAD

**Issue by carior** [AgoraIO/RTM#29]
I want to open two browser Windows for communication session, I tried but failed, always prompt /* server has received, but remote users can not reach the processing logic */. So what should I do to achieve communication with each other?
![image](https://user-images.githubusercontent.com/30487186/63329524-b27a0d80-c364-11e9-9e36-1bffa9b3016b.png)

**Comment by carior** [comment]
Sorry to bother you. I have solved it

**Comment by Matrixbirds** [comment]
You did login the same `account` with the same `appId` twice when you open the second window. BTW, It is important to don't expose your `appId` on Github. I think you need obtain a new one.

**Comment by carior** [comment]
Thank you for your reply. This appid is for my test, and I use dynamic token, others should not log in.



------------------ 原始邮件 ------------------
发件人: "matrixbirds"<notifications@github.com>;
发送时间: 2019年8月20日(星期二) 晚上11:12
收件人: "AgoraIO/RTM"<RTM@noreply.github.com>;
抄送: "悠然时光"<992819526@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [AgoraIO/RTM] communication  (#29)




You did login the same account with the same appId twice when you open the second window. BTW, It is important to don't expose your appId on Github. I think you need obtain a new one.
