### ISSUE TITLE
Call Invite unexpected behaviour 

### ISSUE THREAD

**Issue by PrashantKT** [AgoraIO/RTM#41]
From one view controller I am sending  a local invite and start the call if accepted from other side.
I am came with scenario where RTM callkit has some mismatched behaviour. 

So From ViewController1 I am sending a Local invite. as soon as block  executes with code 0. I am canceling the local invite with object I have sent.  

But problem is how can I notify other user because any of the delegate method is not called on other side. 

Again after that I again send the local invite. so when that received  by callee. and when He try to accept / refuse the local invite there is an error that  AgoraRtmInvitationApiCallErrorNotStarted

 please let me know How can I contact to Agora Team for the support .as I have been added too many git issues in different repos. but from none of them I got a proper answer. 

Best
Prashant

**Comment by plutoless** [comment]
@PrashantKT 
i just tried sending local invitation and cancel it afterwards, it works fine for me. the delegate method is 
func rtmCallKit(_ callKit: AgoraRtmCallKit, remoteInvitationCanceled remoteInvitation: AgoraRtmRemoteInvitation) {
under AgoraRtmCallDelegate
and you need to set the delegate instance to AgoraRtm.kit?.getRtmCall()?.callDelegate

When you send the local invitation again i guess you are using the same invitation object, and because that was cancelled already, so getting not started error looks correct.

i'm sorry for the inconvenience caused for you when using agora samples. you may take a more deeper look into agora official website docs before asking, or you can contact the community team via approaches listed in https://docs.agora.io/en/Agora%20Platform/community?_ga=2.7995442.1887031822.1573724841-2140392182.1568170006

**Comment by ashwiniShet-ios** [comment]
Hi, I am not able to find any code examples to send and receive call. As i am new to Swift feeling it very difficult to develop. Can u pls suggest code samples. Pls

**Comment by plutoless** [comment]
@ashwiniShet-ios 
you can find it https://github.com/AgoraIO-usecase/video-calling
but we indeed only has swift example for now.

**Comment by ashwiniShet-ios** [comment]
Thank you so much for sharing this link. It really helped a lot

**Comment by ashwiniShet-ios** [comment]
Hi, call invitations are working in active state. But not able to implement for inactive state. (Tried with push kit). Anyone can help or any reference code?

**Comment by plutoless** [comment]
@ashwiniShet-ios you have to use with combination of push kit to achieve this yes.

**Comment by RahulFate** [comment]
Hi,
I send multiple invitation and if one of invitation is accepted then all other invitations wants to cancel. How can i achieve this.
i tried to achive this but i face this error code 2

**Comment by plutoless** [comment]
is there any chance that you can share your code snippet so we can understand how you are using?

**Comment by RahulFate** [comment]
For sending multiple invitation, i did following code and it works well.
// Mark:- For sending multiple invitation

 for index in self.userQueryStatusNameArray{
                let rtm = AgoraRtm.shared()
                let invitation = AgoraRtmLocalInvitation(calleeId: index)
                invitation.channelId = self.channelNameWithUnitNo
                invitation.content = myExtraString
                rtm.lastOutgoingInvitation = invitation
                
                guard let inviter = AgoraRtm.shared().inviter else {
                    print("rtm inviter fail")
                    return
                }
                inviter.send(invitation) { [unowned rtm] (errorCode) in
                    guard errorCode == AgoraRtmInvitationApiCallErrorCode.ok else {
                        print("error invitation - \(errorCode.rawValue)")
                        return
                    }
                }
}


// below is code when any one user accept call after receiving  invitation and user join channel. and other users who receive invitations are cancel by using cancellocalInvation method.

func inviter(_inviter:AgoraRtmCallKit,didAcceptIncoming invitation: AgoraRtmInvitation,channelId:String){
       print("accept call callee  - \(invitation.callee)")
         print("accept call caller  - \(invitation.caller)")
        print("user query array is : -  \(self.userQueryStatusNameArray)")
        if self.self.userQueryStatusNameArray.count > 0
                   {
                       for index in self.userQueryStatusNameArray
                       {
                           if invitation.callee != index
                           {
                            guard let inviter = AgoraRtm.shared().inviter else {
                                                   fatalError("rtm inviter nil")
                                               }
                            let errorHandle: ErrorCompletion = { [weak self] (error: AGEError) in
                                                   print(error.localizedDescription)
                                               }
                          // write cancel invitation code with index as id
   inviter.cancelLastOutgoingInvitation(fail: errorHandle)
                           }
                       }
                   }
        agoraKit.joinChannel(byToken: nil, channelId: channelId, info:nil, uid:0)
    }

//Mark:-  cancel last outgoing invitation method

 func cancelLastOutgoingInvitation(fail: ErrorCompletion = nil) {
        let rtm = AgoraRtm.shared()
        guard let last = rtm.lastOutgoingInvitation else {
            return
        }
        print("this is the last - \(String(describing: last.content))")
        print("this is the last callee id - \(String(describing: last.calleeId))")
        cancel(last) { (errorCode) in
            guard errorCode == AgoraRtmInvitationApiCallErrorCode.ok else {
                   print("rtm cancel invitation fail: \(errorCode.rawValue)")
                return
            }
        }
        rtm.lastOutgoingInvitation = nil
    }

if i use above method then only last outgoing invitation is cancel.  But i would like to cancel all invitation except the user who accept call invitation.

Please help me out for this scenerio.

**Comment by RahulFate** [comment]
For sending multiple invitation, i did following code and it works well.
// Mark:- For sending multiple invitation
` for index in self.userQueryStatusNameArray{
                let rtm = AgoraRtm.shared()
                let invitation = AgoraRtmLocalInvitation(calleeId: index)
                invitation.channelId = self.channelNameWithUnitNo
                invitation.content = myExtraString
                rtm.lastOutgoingInvitation = invitation
                
                guard let inviter = AgoraRtm.shared().inviter else {
                    print("rtm inviter fail")
                    return
                }
                inviter.send(invitation) { [unowned rtm] (errorCode) in
                    guard errorCode == AgoraRtmInvitationApiCallErrorCode.ok else {
                        print("error invitation - \(errorCode.rawValue)")
                        return
                    }
                }
}`

// below is code when any one user accept call after receiving  invitation and user join channel. and other users who receive invitations are cancel by using cancellocalInvation method.
`func inviter(_inviter:AgoraRtmCallKit,didAcceptIncoming invitation: AgoraRtmInvitation,channelId:String){
       print("accept call callee  - \(invitation.callee)")
         print("accept call caller  - \(invitation.caller)")
        print("user query array is : -  \(self.userQueryStatusNameArray)")
        if self.self.userQueryStatusNameArray.count > 0
                   {
                       for index in self.userQueryStatusNameArray
                       {
                           if invitation.callee != index
                           {
                            guard let inviter = AgoraRtm.shared().inviter else {
                                                   fatalError("rtm inviter nil")
                                               }
                            let errorHandle: ErrorCompletion = { [weak self] (error: AGEError) in
                                                   print(error.localizedDescription)
                                               }
                          // write cancel invitation code with index as id
   inviter.cancelLastOutgoingInvitation(fail: errorHandle)
                           }
                       }
                   }
        agoraKit.joinChannel(byToken: nil, channelId: channelId, info:nil, uid:0)
    }`

//Mark:-  cancel last outgoing invitation method

`func cancelLastOutgoingInvitation(fail: ErrorCompletion = nil) {
        let rtm = AgoraRtm.shared()
        guard let last = rtm.lastOutgoingInvitation else {
            return
        }
        print("this is the last - \(String(describing: last.content))")
        print("this is the last callee id - \(String(describing: last.calleeId))")
        cancel(last) { (errorCode) in
            guard errorCode == AgoraRtmInvitationApiCallErrorCode.ok else {
                   print("rtm cancel invitation fail: \(errorCode.rawValue)")
                return
            }
        }
        rtm.lastOutgoingInvitation = nil
    }
`

if i use above method then only last outgoing invitation is cancel.  But i would like to cancel all invitation except the user who accept call invitation.

Please help me out for this scenerio.

**Comment by plutoless** [comment]
@RahulFate from your code above. your lastOutgoingInvitation will always be the last element in your name array.you will need to maintain an invitation array and loop over that.

**Comment by RahulFate** [comment]
Thanks @plutoless . I did it same way I store all sending invitations in an array. And if any invitation is accepted then other invitations cancel using cancel local invitation.
I used agora in my two applications.

**Comment by plutoless** [comment]
@RahulFate from your above code you are only cancelling the last one.

**Comment by RahulFate** [comment]
Yes. If I used this then I can cancel only last invitation. So I store all objects in array of invitations.

**Comment by plutoless** [comment]
so is the issue resolved?

**Comment by RahulFate** [comment]
Yes. Issue is resolved .

**Comment by plutoless** [comment]
OK good to know

**Comment by masum1161** [comment]
is it work for android?
