### ISSUE TITLE
Real-Time Messaging Sample code Login Error

### ISSUE THREAD

**Issue by AbhijithEnfinTechnologies** [AgoraIO/RTM#49]
I have downloaded RTM sample code . And also give our appID. But always shows Login failed message after give a unique account / UserId.

**Comment by plutoless** [comment]
if you have turned out token feature, you will have to calculate a token for your user account to login properly.

**Comment by AbhijithEnfinTechnologies** [comment]
We don't change that feature.

**Comment by plutoless** [comment]
i saw in the other thread, it seems you are already using a token. could you pls post a temp token and account you are using so that i can take a look

**Comment by AbhijithEnfinTechnologies** [comment]
Thanks now its working. The issue from the token generation.

**Comment by Moadams** [comment]
How did you solve it, please? I am facing the same error and don't know how to proceed.
