### ISSUE TITLE
Persistent Messaging

### ISSUE THREAD

**Issue by hkgittt** [AgoraIO/RTM#53]
There is an option to persist messages on send on both `RTMClient.sendMessageToPeer()` and `RTMChannel.sendMessage()` methods via the `SendMessagesOptions` interface (which is the optional second parameter on both methods).

However I cannot find information on how and in what form these messages are persisted, and ultimately on how to retrieve the messages history.

Can someone point me in the right direction please? Thank you.

**Comment by plutoless** [comment]
message history is not yet a published feature. for now you need to persist the message on your own server.

**Comment by hkgittt** [comment]
Thanks for the clarification @plutoless.

Is there a timeframe for when it will be published?
Also, you should specify this on the doc where relevant.

**Comment by plutoless** [comment]
usually anything not specified in doc means it's not supported officially. the timeline is not yet clear for now, what i know is there is some internal development going on.

**Comment by hkgittt** [comment]
The relevant page on the doc I meant was this [page](https://docs.agora.io/en/Real-time-Messaging/API%20Reference/RTM_web/interfaces/sendmessageoptions.html#enablehistoricalmessaging). Not trying to be an ass, just trying to be helpful 🙂

**Comment by plutoless** [comment]
@hkgittt thx for pointing out. i was not realizing that sry. i confirmed with my colleagues, it's shown there but still in beta phase. if you believe you need this feature maybe you can try contacting sales person.
