### ISSUE TITLE
Trying to login always gives the error `RtmUnauthenticatedError: Error Code 5. Signature verification failed`

### ISSUE THREAD

**Issue by kush3107** [AgoraIO/RTM#70]
Hi, I am trying to login on Rtm Client but always get the specified error. I am creating a token from my server in the exact same manner as I create for the live video streaming. Also the it uses the same App Id and Certificate.

`The Agora RTM Web SDK version is 1.2.2. +0ms`

I get the above error when I pass the `token` as the parameter while logging in, on the other hand if I do not have provide the token I get the [https://github.com/AgoraIO/RTM/issues/28](#28 )

**Comment by kush3107** [comment]
I figured that out. There is a different Rtm Token generator. https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/nodejs/sample/RtmTokenBuilderSample.js

**Comment by norbertsongin** [comment]
To whoever experiences this issue, make sure you're using `RtmTokenBuilder` and not `RtcTokenBuilder` like I did
