### ISSUE TITLE
RTM not working on iOS

### ISSUE THREAD

**Issue by zontan** [AgoraIO/RTM#80]
RTM appears to be broken on iOS. Logging in does not work on the sample app - it results in a timeout error (error code 9). This is with an app ID with RTM enabled and no token authentication.

**Comment by plutoless** [comment]
@digitallysavvy can you reproduce this?

**Comment by digitallysavvy** [comment]
I just tested and I was able to get the demo to work. I will reach out to @zontan and see if we can resolve his issue.

**Comment by zontan** [comment]
The issue appears to be due to my phone specifically - restarting the device resolved the problem.
