### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by chandruscm** [AgoraIO/RTM#81]
I'm building for Android, my project could not resolve these 3 classes. Which version supports these classes?

io.agora.rtm.RtmFileMessage
io.agora.rtm.RtmImageMessage
io.agora.rtm.RtmMediaOperationProgress

I'm using RTM SDK version 1.2.2. I tried adding the sdk as a gradle dependency as well as the local jar.

**Comment by plutoless** [comment]
please download latest 1.3.0 sdk from our official website

**Comment by chandruscm** [comment]
Thanks @plutoless 😊 I was able to fetch it from the maven repository.

Updating the [release notes](https://docs.agora.io/en/Real-time-Messaging/release_android_rtm?platform=Android), [quick start guide](https://docs.agora.io/en/Real-time-Messaging/messaging_android?platform=Android) and [SDK downloads](https://docs.agora.io/en/Agora%20Platform/downloads) would be good idea.
