### ISSUE TITLE
agora-rtm-sdk-1.2.2.js:7 RTM:ERROR Error Code 5. The vendor enabled the dynamic key, but uses the static key.

### ISSUE THREAD

**Issue by maheshpraj** [AgoraIO/RTM#94]
I also getting same issue. please how can solve it. i try but cant works.
I am used for web application. "**agora-rtm-sdk-1.2.2.js**"
var client = AgoraRTM.createInstance(option.appID);
client.login({ token: mToken, uid: uid.toString() }).then(function () {
console.log('AgoraRTM client login success');
}).catch(function (err) {
console.log('AgoraRTM client login failure', err);
});

**Comment by plutoless** [comment]
hi this means you have turned on security token, you will need to take it when joining channel
please read https://docs.agora.io/en/Agora%20Platform/token for details

**Comment by maheshpraj** [comment]
I already turned on security token. PFA
![2020-07-27 14_18_19-Edit Project](https://user-images.githubusercontent.com/49314670/88576914-311b0880-d014-11ea-8144-80481e179ae3.png)

**Comment by plutoless** [comment]
@maheshpraj 
if you have turned on token, you will have to generate a token and use it when join channel. For tutorials of how to generate a token has been put in the link i provided in previous comments.
If you have not turned on token, you will be able to join channel with APPID only. if you just want to test out, you may create a new project w/o token first.

**Comment by plutoless** [comment]
@maheshpraj 
if you have turned on token, you will have to generate a token and use it when join channel. For tutorials of how to generate a token has been put in the link i provided in previous comments.
If you have not turned on token, you will be able to join channel with APPID only. if you just want to test out, you may create a new project w/o token first.
