### ISSUE TITLE
【BUG】断线重连，频道相关回调均失效

### ISSUE THREAD

**Issue by chudongvip** [AgoraIO/RTM#97]
SDK: RTM SDK

步骤：
1. A login
2. A join channel
3. 断网
4. 连网，出现重连错误若干次之后
5. B join channel
6. B send a channel message
7. A 没有收到消息

User A：
![image](https://user-images.githubusercontent.com/31001856/89155158-e14fba80-d59a-11ea-8c8c-3f481b55ccef.png)

User B:
![image](https://user-images.githubusercontent.com/31001856/89155179-e7de3200-d59a-11ea-86f7-41765ca0abe0.png)

**Comment by shellGrace** [comment]
您好，关于「A 加入频道后，断网。此时 B 发频道消息，并且成功发送到频道。A 无法收到离线时的频道消息」是预期行为。但在 A 重新连接网络后，sdk 会自动做重新登录恢复到原始状态的行为，此时 B 再发消息，A 可以收到。您可以通过在我们示例 demo 里监听 ConnectionStateChanged 网络状态的地方去打印回调中的状态，可实时看到当前状态码，通过状态码在我们的官网文档中查阅相关信息

**Comment by chudongvip** [comment]
> 您好，关于「A 加入频道后，断网。此时 B 发频道消息，并且成功发送到频道。A 无法收到离线时的频道消息」是预期行为。在 A 重新连接网络后，sdk 会自动做重新登录恢复到原始状态的行为，此时 B 再发消息，A 可以收到。您可以通过在我们示例 demo 里监听 ConnectionStateChanged （查看 sdk 与后台的连接状态）的地方去打印回调参数，可实时看到当前状态和状态改变的原因。通过打印的参数，可在我们的官网文档中查阅对应的信息。

谢谢回复，但是我发送的是离线消息给A，按理A再次上线是可以收到该离线消息的把
